development:
  admin_username: First User
  admin_email: admin@festivalblog.de
  admin_password: changeme

production:
  admin_username: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
